config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'vehicles#index'
  get 'profiles', to: 'profiles#show', as: :profile
  patch 'bookings/:id', to: 'bookings#validation', as: :validation

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :vehicles do
    resources :bookings, only: %i[new create edit update]
    resources :reviews, only: %i[new create edit update]
  end
  resources :bookings, only: [:destroy]
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :vehicle
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :vehicle
  has_many :users, through: :vehicles
  validates :content, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :photo
  has_many :vehicles, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :vehicles
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  before_save :images_limit_min
  has_many_attached :photos
  has_many :reviews, dependent: :destroy
  belongs_to :user
  has_many :bookings
  validates :name, uniqueness: true, presence: true
  # validates :photos, attached: true, limit: { min: 3, max: 5 }

  private

  def images_limit_min
    return if photos.empty?

    errors[:base] << "You must to upload 3 images minimum" if photos.length < 3
    errors[:base] << "You must to upload 5 images max" if photos.length > 5
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name address photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name address photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new(booking_params)
    @vehicle = Vehicle.find(params[:vehicle_id])
    @vehicle.available = false
    @booking.vehicle = @vehicle
    @booking.save
    @booking.user_id = current_user.id


    if @booking.end_date && @booking.start_date
      number_of_day = @booking.end_date - @booking.start_date
      @booking.full_price = @vehicle.price_per_day * number_of_day.floor
      if @booking.full_price.positive?
        @booking.save

        if @booking.save
          redirect_to vehicle_path(@vehicle), notice: "Your request have been submited !!!"
        else
          redirect_to vehicle_path(@vehicle), alert: "Something went wrong, try again"
        end
      else
        redirect_to vehicle_path(@vehicle), alert: "You should give valid date"
      end

    else
      redirect_to vehicle_path(@vehicle), alert: "You should valid date"
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to profile_path, alert: "Your booking is deleted"
  end

  def validation
    @booking = Booking.find(params[:id])
    @booking.validated = true
    @booking.save
    redirect_to profile_path, notice: "Your rent is confirmed"
  end
end

private

def booking_params
  params.require(:booking).permit(:start_date, :end_date, :full_price, :vehicle, :user)
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/profiles_controller.rb
require 'open-uri'

class ProfilesController < ApplicationController
  def show
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @vehicle = Vehicle.find(params[:vehicle_id])
    @review = @Review.new
  end

  def create
    @vehicle = Vehicle.find(params[:vehicle_id])
    @review = Review.new(review_params)
    @review.vehicle = @vehicle
    if @review.save
      redirect_to vehicle_path(@vehicle)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to vehicle_path
  end
end

private

def review_params
  params.require(:review).permit(:content, :rating, :vehicle)
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: %i[show edit update destroy]
  def index
    if params[:query].present?
      sql_query = "name ILIKE :query"
      @vehicles = Vehicle.where(sql_query, query: "%#{params[:query]}%")
    else
      @vehicles = Vehicle.all
    end
    if user_signed_in?
      current_user.vehicles.each do |vehicle|
        to_validated = vehicle.bookings.select { |el| el.validated == false }.count
        if to_validated.positive?
          flash.alert = "You got #{to_validated} Rent#{to_validated > 1 ? 's' : ''} to validated"
        end
      end
      validated = current_user.bookings.last
      if validated && (validated.validated == true)
        flash.alert = "Your booking of #{validated.vehicle.name} have been confirm by #{validated.vehicle.user.email}"
      end
    end
  end

  def show
    @vehicle = Vehicle.find(params[:id])
    @booking = Booking.new
    @reviews = []
    @review = Review.new(vehicle: @vehicle)
    @vehicle.reviews.each do |review|
      @reviews << Review.find_by(id: review)
    end
  end

  def new
    @vehicle = Vehicle.new
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    @vehicle.user = current_user
    @vehicle.save
    if @vehicle.save
      redirect_to vehicle_path(@vehicle)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @vehicle.update(vehicle_params)

    redirect_to vehicle_path(@vehicle)
  end

  def destroy
    @vehicle.destroy

    redirect_to vehicles_path
  end

  private

  def set_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

  def vehicle_params
    params.require(:vehicle).permit(:name, :price_per_day, :year, :category, :description, :user_id, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KittflixApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/footer' %>
    <% if notice %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
          <%= notice %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>

    <% if alert %>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <%= alert %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>


    <%= yield %>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/profiles/show.html.erb
<div class="card-profile">
  <div class="avatar-profile" style="height: 150px; width: 150px; background-size:cover; background-position: center; background-image: linear-gradient(rgba(0,0,0,0.0), rgba(0,0,0,0.0)), url('<%= current_user.photo.attached? ? cl_image_path(current_user.photo.key) : asset_path('Default-avatar.jpg')%>')">
  </div>

  <!--<div class="title-avatar"><h3 class="style-email"><%= current_user.email %></h3>-->
  <h3 class="style-fullname"><%= current_user.first_name %>  <%= current_user.last_name %></h3>
  </div>
</div>

<div class="container-btn">
  <div style="margin:16px">
    <%= link_to 'Add a car', new_vehicle_path, class: "btn-add btn btn-light"  %>
  </div>


  <div style="margin:16px">
    <%= link_to 'Edit your profile', edit_user_registration_path, class: "btn-edit btn btn-light"  %>
  </div>
</div>



<div class="container-rents">
    <h4 style="color:white">Rents to validate</h4>
      <div style="margin:16px">
        <% current_user.vehicles.each do |vehicle| %>
            <% to_validated = vehicle.bookings.select {|el| el.validated == false}.count %>
              <% if to_validated.positive? %>
                <p style="color:white">You still got <%= to_validated %> Rent<%= to_validated > 1 ? 's' : '' %> to validated</p>
              <% end %>
          <% end %>
      </div>

    <h4 style="color:white">Bookings awaiting validation</h4>
      <div>
        <% not_validated = current_user.bookings.select {|el| el.validated == false}.count%>
            <% if not_validated.positive? %>
              <p style="color:white">You still got <%= not_validated %> Booking<%= not_validated > 1 ? 's' : '' %> not validated</p>
            <% end %>
      </div>
</div>






    <h5 class="title-card">All your Cars</h5>
    <div class="cards">
      <% current_user.vehicles.each do |vehicle| %>
        <div class="card-category" style="background-image: linear-gradient(rgb(0 0 0 / 30%),rgb(0 0 0 / 30%)), url('<%= cl_image_path vehicle.photos.first.key %>')">
          <br>
          <ul>
          <li><%= vehicle.name %></li>
          <%= link_to edit_vehicle_path(vehicle) do %>
           <li><i class="fa-solid fa-pencil"></i></li>
          <% end %>
          <%= link_to vehicle_path(vehicle), method: :delete, data: { confirm: "Are you sure?" } do %>
            <li><i class="fa-solid fa-trash"></i></li>
          </ul>
            </div>
          <% end %>
      <% end %>
    </div>


      <h5 class="title-card">All your Bookings</h5>
        <div class="cards">
            <% current_user.bookings.each do |booking| %>
                <ul>
                  <li><%= booking.vehicle.user.email %></li>
                  <li><%= booking.vehicle.name %></li>
                  <li><%= booking.start_date %></li>
                  <li><%= booking.end_date %></li>
                  <li><%= booking.full_price %></li>

                <% if booking.validated == false %>
                    <%= link_to booking_path(booking), method: :delete, data: { confirm: "Are you sure?" } do %>
                      <li><i class="fa-solid fa-trash"></i></li>
                    <% end %>
                    <li><i class="fa-solid fa-square-check" style="color:red; font-size: 20px"></i></li>
                  <% else %>
                    <li><i class="fa-solid fa-square-check" style="color:green; font-size: 20px"></i></li>
                  <% end %>
                </ul>
            <% end %>
        </div>


    <h5 class="title-card">All your Rents</h5>
    <div class="cards">
        <% current_user.vehicles.each do |vehicle| %>
          <% vehicle.bookings.each do |rent| %>
            <ul>
              <li><%= rent.user.email %></li>
              <li><%= rent.start_date %></li>
              <li><%= rent.end_date %></li>
              <li><%= rent.full_price %></li>
              <% if rent.validated == false %>
                <%= link_to 'Confirm', validation_path(rent), method: :patch  %>
                <%= link_to booking_path(rent), method: :delete, data: { confirm: "Are you sure?" } do %>
                  <li><i class="fa-solid fa-trash"></i></li>
                <% end %>
              <% else %>
                <li><i class="fa-solid fa-square-check" style="color:green; font-size: 20px"></i></li>
              <% end %>
            </ul>
          <% end %>
        <% end %>
    </div>

app/views/shared/_navbar.html.erb
<div id="app">
   <nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation">
     <div class="container">
       <div class="navbar-brand">
        <%= link_to vehicles_path do %>
           <%= image_tag "KITTFLIX.png" %>
        <% end %>
       </div>
         <div class="navbar-links">
            <ul>
              <li>
                <%= link_to vehicles_path do %>
                <%= 'Home' %>
                <% end %>
              </li>
              <li>
                <%= link_to profile_path do %>
                <%= 'My list' %>
                <% end %>
              </li>
            </ul>
          </div>
        <div class="search-bar-nav">
        <%= form_tag vehicles_path, method: :get, class: "search-bar" do %>
            <%= text_field_tag :query,
              params[:query],
              placeholder: "Search"%>
            <%= submit_tag "", class: "search-btn" do %>
              <span>Search</span>
            <% end %>
        <% end %>

              <%# <form action="" class="search-bar">
                <input type="search" name="search"  required>
                <button class="search-btn" type="submit">
                  <span>Search</span>
                </button>
              </form> %>
        </div>
          <li class="nav-item dropdown">
           <div class="avatar-square">
           <% if current_user %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
             <% else %>
             <%= image_tag "profilnetflix.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% end %>
              <div class="dropdown-menu dropdown-menu-end dropdown-menu-dark" aria-labelledby="navbarDropdown">
              <% if user_signed_in? %>
                <%= link_to "Profile", profile_path(current_user), class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, method: :delete ,  class: "dropdown-item" %>
                <%# <%= link_to 'Edit profile', edit_user_registration_path, class: "dropdown-item" %>
                <% else %>
                <%= link_to 'Sign up',  new_user_registration_path, class:'dropdown-item' %>
                <%= link_to 'Sign in', user_session_path, class: "dropdown-item" %>
                <% end %>
                <%# <%= link_to "Log Out", "#", class: "dropdown-item" %>
                <%#= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </div>
          </li>
       </div>
    </nav>
</div>

app/views/vehicles/edit.html.erb
<h2>Edit your car</h2>

<div>
  <%= simple_form_for [ @vehicle ] do |f| %>
    <%= f.input :name %>
    <%= f.input :price_per_day %>
    <%= f.input :category %>
    <%= f.input :description %>
    <%= f.input :year %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.submit "update vehicle", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/vehicles/index.html.erb
 <div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel" data-interval="10">
  <div class="banner carousel-inner">
    <div class="carousel-item active">
          <h1 class="title-kitt"><span class="small-h1">bring </span>FICTION<span class="small-h1"> to</span><br>REALITY</h1>
      <img src="https://www.wallpaperuse.com/wallp/18-189386_m.jpg" class=""  alt="...">
    </div>
    <div class="carousel-item">
          <h1 class="title-delorean"><span class="small-h1"></span>Roads? Where we’re going, <br> we don’t need roads.<span class="small-h1"></span><br></h1>
      <img src="https://wallpaperaccess.com/full/1333809.jpg" class="" alt="...">
    </div>
    <div class="carousel-item">
          <h1 class="title-batmobile"><span class="small-h1"></span>WHY<span class="small-h1">so </span>SERIOUS?</h1>
      <img src="https://wallpaperaccess.com/full/1165268.jpg" class="" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
</div>

    <h3 class="title-card">Popular on Kittflix</h3>
<div class="cards">
      <% @vehicles.each do |vehicle| %>
        <%= link_to vehicle_path(vehicle), :action => 'go' do %>
          <div class="card-category" style="background-image: linear-gradient(rgb(0 0 0 / 30%),rgb(0 0 0 / 30%)), url('<%= cl_image_path(vehicle.photos[0].key)%>')">
            <h3><%= vehicle.name %></h3>
          </div>
        <% end %>
      <% end %>
      </div>

    <h3 class="title-card">Top picks for you</h3>
    <div class="cards">
      <% @vehicles.each do |vehicle| %>
              <%= link_to vehicle_path(vehicle), :action => 'go' do %>
          <div class="card-category" style="background-image: linear-gradient(rgb(0 0 0 / 30%),rgb(0 0 0 / 30%)), url('<%= cl_image_path(vehicle.photos.first.key) %>')">
                <h3><%= vehicle.name %></h3>
              </div>
              <% end %>
            <% end %>
            </div>

    <h3 class="title-card">Only on Kittflix</h3>
    <div class="cards">
      <% @vehicles.each do |vehicle| %>
              <%= link_to vehicle_path(vehicle), :action => 'go' do %>
           <div class="card-category" style="background-image: linear-gradient(rgb(0 0 0 / 30%),rgb(0 0 0 / 30%)), url('<%= cl_image_path(vehicle.photos.first.key) %>')">
                <h3><%= vehicle.name %></h3>
              </div>
              <% end %>
            <% end %>
          </div>
</div>

app/views/vehicles/new.html.erb
<h2>Add new car</h2>

<div class="text-white">
  <%= simple_form_for [ @vehicle ] do |f| %>
    <%= f.input :name %>
    <%= f.input :price_per_day %>
    <%= f.input :category %>
    <%= f.input :description %>
    <%= f.input :year %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.submit "create car", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/vehicles/show.html.erb
<br><br>
<p class="name-title text-white text-center"><%= @vehicle.name %></p>


<div class="parent">
  <% @vehicle.photos.each_with_index do |photo, index|  %>
    <div class="div<%= index + 1 %>">
      <%= cl_image_tag photo.key, height: "100%", width: "100%" %>
    </div>
  <% end %>
</div>


<div class="row mt-5 mb-5 mx-3">
  <div class="col-sm-8 ">
    <div class="card bg-transparent">
      <div class="card-body text-white">

          <div class="card bg-transparent">

                <div class="d-flex justify-content-between mb-3 border-bottom">
                 <div>
                  <p class="text-start"><%= @vehicle.description %></p>
                </div>
                <div class="d-flex justify-content-between">
                <div class="pb-3">
                  <%= cl_image_tag @vehicle.user.photo.key, class: "avatar-large"  %>
                </div>
              <div>
                <p class="text-right"><%= @vehicle.user.last_name %> <%= @vehicle.user.first_name %></p>
              </div>
            </div>
              </div>
          </div>

          <dl>
            <dt class="col-sm-3">Year</dt>
            <dd class="col-sm-9"><%= @vehicle.year %></dd>

            <dt class="col-sm-3">Type</dt>
            <dd class="col-sm-9">
              <p><%= @vehicle.category %></p>
            </dd>
            <dt class="col-sm-3">Available</dt>
            <dd class="col-sm-9"><%= @vehicle.available ? "Yes" : "Not for the moment" %></dd>


            <dt class="col-sm-3">Price</dt>
            <dd class="col-sm-9"><%= @vehicle.price_per_day %></dd>

          </dl>
      </div>
  </div>
  </div>
<% if user_signed_in? %>
  <% unless current_user.id == @vehicle.user.id %>
    <div class="col-sm-4">
      <div class="card bg-dark">
        <div class="card-body">
          <div class="text-center mt-0">
            <h3 class="font-weight-bold text-white">Choose your dates</h3>
          </div>

            <div class="text-center text-white">
                    <%= simple_form_for [@vehicle, @booking] do  |f| %>
                <%= f.input :start_date, as: :date, html5: true %>
                <%= f.input :end_date, as: :date, html5: true %>
                  <div class="text-center">
                    <%= f.button :submit, 'Rent', class: "text-center btn btn-danger" %>
                  </div>
                <% end %>
            </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>


<div class="reviews">
  <h5 class="mx-3">Comments :</h5>

<% @reviews.each do |review|%>
    <div class="card-product mx-5 bg-dark">
      <div class="card-product-infos">
      <% review.rating.to_i.times do  %>
        <i class="fa fa-star" aria-hidden="true" style="font-size: 20px; color:goldenrod"></i>
      <% end %>
         <p><%= review.content %></p>
         <%= review.vehicle.user.first_name  %>

      </div>
    </div>
  <% end %>

<div class="m-5 p-5">
  <div class="card mb-2">
    <div class="card-body mx-2">
      <%= simple_form_for([@vehicle, @review], remote: true) do  |f| %>
        <%= f.input :content, placeholder: "How was the trip ?"%>
        <%= f.input :rating, as: :select, collection: (1..5), required: true, prompt: "How would you rate the trip ?", input_html: { data: { controller: "jquery-bar-rating" } } %>
        <%= f.submit class:"btn btn-flat" %>
      <% end %>
  </div>
</div>